# Copy to /mnt/data/wireguard/wg0.conf

[Interface]
Address = 10.1.2.1/24
PrivateKey = < add private key>
PostUp = /etc/wireguard/add-nat-routing.sh
PostDown = /etc/wireguard/remove-nat-routing.sh
ListenPort = 51820

[Peer]
# Work Laptop
PublicKey =  < add pub key >
AllowedIPs = 10.1.2.10/32

[Peer]
# iPhone
PublicKey =  < add pub key >
AllowedIPs = 10.1.2.11/32
