{
 "title": "CoreDNS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CoreDNS CPU usage (sec/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"coredns-*\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg DNS Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(coredns_dns_request_count_total[2m])) by (proto)",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=~\"coredns-*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit bits per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"coredns-.*\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Rate of DNS Requests by type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total[2m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Receive bits per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"coredns-.*\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}